### ISSUE TITLE
请问支持华为昇腾910b吗

### ISSUE THREAD

**Issue by tommy3266** [safevideo/autollm#178]

**Comment by SeeknnDestroy** [comment]
Hi @tommy3266,

Can you please help me better understand your problem via explaining it in Englsh please?

**Comment by tommy3266** [comment]
> Hi @tommy3266,
> 
> Can you please help me better understand your problem via explaining it in Englsh please?

Can this autollm framework run on huawei Kylin V10，npu?，

**Comment by SeeknnDestroy** [comment]
If your device supports `python==3.10`, `autollm` will surely work as expected!
