### ISSUE TITLE
Local embedding model not working

### ISSUE THREAD

**Issue by AbrahimZaman360** [safevideo/autollm#199]
LLM Provider is not provided. because you have passed "Local"

**Comment by SeeknnDestroy** [comment]
Hi @AbrahimZaman360,

Thank you for pointing that out. I will update the README for correct use case of `embed_model` with our newly added `AutoEmbedding` class.

For quick solution, please refer to https://github.com/safevideo/autollm/discussions/193#discussioncomment-8030537 on how you can specify a local embedding model.

**Comment by AbrahimZaman360** [comment]
> Hi @AbrahimZaman360,
> 
> Thank you for pointing that out. I will update the README for correct use case of `embed_model` with our newly added `AutoEmbedding` class.
> 
> For quick solution, please refer to https://github.com/safevideo/autollm/discussions/193#discussioncomment-8030537 on how you can specify a local embedding model.

Is it usual that results take 1 min to generate.

**Comment by SeeknnDestroy** [comment]
we have detailed logging for you to be able to follow what is done under the hood step-by-step. It's heavily dependent on the document sizes.

**Comment by SeeknnDestroy** [comment]
and unfortunately, openai embeddings works bit faster @AbrahimZaman360

**Comment by AbrahimZaman360** [comment]
> and unfortunately, openai embeddings works bit faster @AbrahimZaman360 

Still taking 1 min to generate response based on query (:

**Comment by fcakyon** [comment]
@AbrahimZaman360 which autollm version are you using?

**Comment by AbrahimZaman360** [comment]
> @AbrahimZaman360 which autollm version are you using?

Current latest

**Comment by fcakyon** [comment]
Which llm model and embedding model are you using?

What is your pipeline? (AutoFastAPI, AutoQueryEngine etc)

**Comment by AbrahimZaman360** [comment]
OpenAI as language model and embed="local"

**Comment by fcakyon** [comment]
embed='local' should raise error on the latest `autollm` release. Are you sure on using the latest `autollm` ?

**Comment by AbrahimZaman360** [comment]
I'm not using embed='local' because of that error you're referring to! I was just wondering why this error coming! If any fix?

**Comment by SeeknnDestroy** [comment]
we don't support using 'local' keyword anymore. Previously, embed='local' was doing the job of using default Huggingface model of 'BAAI/bge-small-en'. We now  specify which huggingface embed model to use. If you still want to use default, please use `embed_model=huggingface/BAAI/bge-small-en`.

**Comment by AbrahimZaman360** [comment]
> we don't support using 'local' keyword anymore. Previously, embed='local' was doing the job of using default Huggingface model of 'BAAI/bge-small-en'. We now specify which huggingface embed model to use. If you still want to use default, please use `embed_model=huggingface/BAAI/bge-small-en`.

litellm.exceptions.APIConnectionError: Model BAAI/bge-small-en is currently loading
