### ISSUE TITLE
How to load PDF and other Docs

### ISSUE THREAD

**Issue by AbrahimZaman360** [safevideo/autollm#60]
How to load PDF and other documents, here are just told about .md

**Comment by SeeknnDestroy** [comment]
Hey @AbrahimZaman360, thanks for checking in!

`required_exts` is an optional parameter in our `read_files_as_documents` and `read_github_repo_as_documents` functions. If you don't want to specify which type of documents you want to be read, then you can easily omit it and read all of our [supported file types](https://github.com/run-llama/llama_index/blob/main/llama_index/readers/file/base.py#L19-L34) :)
