### ISSUE TITLE
Quickstart has undefined objects leading error

### ISSUE THREAD

**Issue by apdullahyayik** [safevideo/autollm#67]
I came across this project on LinkedIn that attracted my attetion. Then I decided to clone it to explore its functionality. Regrettably, I encountered issues with the quick start instructions provided in the Readme.md file. 

```python
query_engine = AutoQueryEngine.from_parameters(documents: List[llama_index.Documents]) 
# documents and llama_index objects are not defined, even List is not defined.
```

I would greatly appreciate it if these instructions could be rectified or alternatively supplemented with a more straightforward example. Thank you.

**Comment by SeeknnDestroy** [comment]
Thank you @apdullahyayik deeply for your attention and valuable feedback. Please refer to our [Quickstart Colab Notebook](https://colab.research.google.com/github/safevideo/autollm/blob/main/examples/quickstart.ipynb) for fully working step-by-step guide. For a quick solution, you can use our `read_files_as_documents` function like following:
```python
from autollm.utils.document_reading import read_files_as_documents

documents = read_files_as_documents(input_dir="your/path/to/documents")
query_engine = AutoQueryEngine.from_parameters(documents=documents) 
```
Your feedback helps us improve; we're grateful for it.

Warm regards,
Talha
