### ISSUE TITLE
Local LLM support

### ISSUE THREAD

**Issue by jonny7737** [safevideo/autollm#68]
With few exceptions, most supported LLMs are 4K context window. Local LLMs at least give the opportunity for 16K, 32K and more.

**Comment by fcakyon** [comment]
Hello @jonny7737, OpenAI provides 16K context windiw models, clause-v2 has 100K context window.

Moreover, you can use any opensource HuggingFace and Ollama models with `autollm` (since we are using LiteLMM underhood). Feel free to ask more questions!

**Comment by jonny7737** [comment]
I was not aware OpenAI and Claude2 could be hosted locally.  I stand corrected.

**Comment by Meathelix1** [comment]
> I was not aware OpenAI and Claude2 could be hosted locally. I stand corrected.

They cant.. The only thing you are hosting locally would be the database that these models speak too, or the model from the Local LLM.

**Comment by fcakyon** [comment]
> I was not aware OpenAI and Claude2 could be hosted locally. I stand corrected.

They don't work locally but they do have a larger context window.

You should use HuggignFace and Ollama models for local alternatives with `autollm`.

**Comment by igoralvarezz** [comment]
> > I was not aware OpenAI and Claude2 could be hosted locally. I stand corrected.
> 
> They don't work locally, but they do have a larger context window.
> 
> You should use HuggignFace and Ollama models as local alternatives with `autollm`.

Is there a way to use local (offline) models from hugginface without the use of Ollama (currently not available for Windows OS yet)?

**Comment by SeeknnDestroy** [comment]
Hello @igoralvarezz 

Yes, you can use local (offline) models from HuggingFace directly. We support all the following types:

1. [Text-generation-interface models](https://huggingface.co/models?other=text-generation-inference)
2. [Conversational task models](https://huggingface.co/models?pipeline_tag=conversational)
3. Non TGI/Conversational-task LLMs

For implementation details and how to integrate them, please refer to our [🌟 features](https://github.com/safevideo/autollm#-features) which contains comprehensive examples. 

Thanks for reaching out, and let us know if you have further questions!

Best,
Talha
